### ISSUE TITLE
Issue with \r appearing in history command

### ISSUE THREAD

**Issue by 0xAdk** [phiresky/ts-histdbimport#2]
hi, when trying to import a history file if any command has a `\r` in it the history entry regex fails
because node's readline sees both `\n` and `\r` as line separators and assumes the rest of the text past the `\r` is a new newline.

I've implemented a fix in my fork, but it's a very crude method where I read the whole file into memory and parse it byte by byte (I don't know much about node so this is the best method I could think of). So I didn't bother sending a pull request.

**Comment by phiresky** [comment]
Mh, interesting issue. Unfortunately the node readline module is ... pretty shitty, and other methods of streamingly reading a file split by lines are much more ugly.

Reading the whole file at once *might* be fine since at maximum a history file is probably ~100MB in size. Then splitting it will probably make it use at least twice as much memory. I've left a few comments on your fork, but I'm not sure if the tradeoff of reading it at once are worth the `\r` fix. When would you have \r in your history except when pasting some command from some Windows file?

**Comment by 0xAdk** [comment]
I only have a few commands with `\r` in them and I don't really remember the context.. looking at my history it seems like I was just trying to put a \n but forgot `ctrl-v` `enter` actually puts a `\r` :sweat_smile:

**Comment by 0xAdk** [comment]
I used your suggestions to clean up the code, I was able to get the loading of the whole file and splitting by unescaped newlines into a single nice readable (to me) line :smile:

doing some simple benchmarks with hyperfine the changes made the total time the command took on my machine go from ~2.5 to ~2.0 seconds on my 72k command history file. So it's definitely better then byte by byte parsing

**Comment by phiresky** [comment]
Looked at your code, splitting by only unescaped newlines is pretty smart. It looks pretty clean now I think. 

I'd merge it but I'm still not sure if the tradeoff of making it break if the file size too large is worth it. Even though that's probably pretty unlikely...

**Comment by phiresky** [comment]
Well, I've merged it anyways in #3 and added a note to the README. We'll see if anyone complains :)
